### ISSUE TITLE
引用LayoutView的类无法释放

### ISSUE THREAD

**Issue by huazhenzhu** [zzz40500/android-shapeLoadingView#11]
即便LayoutView不可见,仍然会无限次数的做"上抛下落"动画

startLoading和stopLoading方法中的mAnimatorSet并没有在后续赋值.而且在stopLoading方法中做anim.cancel前应该移除动画监听.即mAnimatorSet.removeAllListeners()

**Comment by zzz40500** [comment]
有空我改改. 谢谢你
