### ISSUE TITLE
not available........pls update

### ISSUE THREAD

**Issue by hkk007** [zzz40500/android-shapeLoadingView#5]
i cant sync this   using   compile 'com.github.zzz40500:android-shapeLoadingView:64e0c03321'

in build.gradle........pls tell me if this is available..............

pls reply ...........

**Comment by hkk007** [comment]
In added from jipack.io ...........but it is declared in manifest  min api level 14..........but i want it in api 10   gingerbread...........how can i change

pls reply

**Comment by zzz40500** [comment]
use
dependencies {
    compile 'com.mingle.zzz40500:shapeloading:1.0.3'
}
it compatibility to android 2.3 (api9)

**Comment by hkk007** [comment]
thanks ...for the reply....i will try
