### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by jitpack-io** [zzz40500/android-shapeLoadingView#9]
Hi,
There seems to be a build error related to resources:
https://jitpack.io/com/github/zzz40500/android-shapeLoadingView/1.0.3/build.log

```
:shapeloading:processReleaseResources 
Position 4:25-47 : No resource found that matches the given name (at 'background' with value '@drawable/aa_dialog_bg').
```

**Comment by sunfusheng** [comment]
lib更新不下来啊

**Comment by zzz40500** [comment]
compile 'com.github.zzz40500:android-shapeLoadingView:1.0.3.2' 这个不行吗?

**Comment by sunfusheng** [comment]
可以了，谢谢你哈，刚才更新了半天没下下来，我的QQ：1021122748。
我在北京工作，可以认识下哈。

**Comment by jitpack-io** [comment]
new version builds great!
https://jitpack.io/com/github/zzz40500/android-shapeLoadingView/1.0.3.2/build.log
